name: Django-Routify Tests

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Django==4.0.0 django-routify

    - name: Verify Python
      run: python --version

    - name: Run unit tests
      run: python -m tests